In [12]:
import os  
import glob  
  
# 设置文件夹路径  
folder_path = r'E:\work\spatio_evo_urbanvisenv_svi\sv\perception_score'  # 请替换为你的文件夹路径  
# 使用glob模块搜索CSV文件  
csv_files = glob.glob(os.path.join(folder_path, '*.csv'))  
# 打印找到的CSV文件列表  
for csv_file in csv_files:  
    print(csv_file)

E:\work\spatio_evo_urbanvisenv_svi\sv\perception_score\beautiful.csv
E:\work\spatio_evo_urbanvisenv_svi\sv\perception_score\boring.csv
E:\work\spatio_evo_urbanvisenv_svi\sv\perception_score\depressing.csv
E:\work\spatio_evo_urbanvisenv_svi\sv\perception_score\lively.csv
E:\work\spatio_evo_urbanvisenv_svi\sv\perception_score\safety.csv
E:\work\spatio_evo_urbanvisenv_svi\sv\perception_score\wealthy.csv

In [13]:
import pandas as pd  

dfs = []
for csv_file in csv_files:
    df = pd.read_csv(csv_file)
    df.set_index(df.columns[0], inplace=True)  
    dfs.append(df)
  
# 使用pd.concat()函数合并DataFrame，这里使用axis=1来按列合并  
combined = pd.concat(dfs, axis=1)

In [20]:
# combined = combined.reset_index(name='iamge_name') 
combined = combined.reset_index() 
combined.head()
# combined.columns

,iamge_name,beautiful,boring,depressing,lively,safety,wealthy
0,12918_91.05522806_29.64954467_201309_90.jpg,0.000000,39.400436,68.050960,99.605637,95.704077,39.924045
1,11825_91.03004569_29.64412556_201309_180.jpg,3.285165,30.129652,56.102032,85.511819,96.274949,35.580360
2,8643_91.1233995_29.6433565_201309_180.jpg,4.066005,41.776000,61.552374,84.885707,85.884543,57.484489
3,5560_91.11352399_29.68657253_201608_270.jpg,4.246289,66.321016,31.815333,99.653947,96.209332,42.033324
4,13932_91.2051021_29.6430633_202108_0.jpg,4.499184,62.730503,90.665665,60.439160,32.649207,20.660156

In [21]:
# 提取列索引  
column_index = combined.columns.tolist()  
column_index

['iamge_name',
 'beautiful',
 'boring',
 'depressing',
 'lively',
 'safety',
 'wealthy']

In [22]:
combined.to_csv(r'E:\work\spatio_evo_urbanvisenv_svi\sv\perception_score\combined.csv', index=False)

In [53]:

file_path1 = r'e:\work\spatio_evo_urbanvisenv_svi\sv\ss.csv'  # 替换为你的第一个CSV文件的路径  
# df1 = pd.read_csv(file_path1, usecols=[0, 2, 3,1,5,18,67,95,14,88,7,53,12,33,49,137])
df1 = pd.read_csv(file_path1)

# 设置第一列为索引值  
df1.set_index(df1.columns[0], inplace=True)

,wall,building;edifice,sky,floor;flooring,tree,ceiling,road;route,bed,windowpane;window,grass,...,pier;wharf;wharfage;dock,crt;screen,plate,monitor;monitoring;device,bulletin;board;notice;board,shower,radiator,glass;drinking;glass,clock,flag
id,,,,,,,,,,,,,,,,,,,,,
10000_91.03441834_29.63851099_201608_0.jpg,0.006616,0.071173,0.414203,0.0,0.016704,0.0,0.422925,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10000_91.03441834_29.63851099_201608_180.jpg,0.085094,0.055938,0.090968,0.0,0.385750,0.0,0.180461,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10000_91.03441834_29.63851099_201608_270.jpg,0.048906,0.031290,0.354977,0.0,0.127178,0.0,0.381883,0.0,0.0,0.000246,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10000_91.03441834_29.63851099_201608_90.jpg,0.032631,0.038755,0.275576,0.0,0.134522,0.0,0.380643,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10000_91.03441834_29.63851099_202107_0.jpg,0.005023,0.055734,0.420267,0.0,0.022732,0.0,0.420103,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [56]:
# df1.head()
df1.iloc[0:5,[0, 2, 3,1,5,18,67,95,14,88,7,53,12,33,49,137]]

,wall,sky,floor;flooring,building;edifice,ceiling,curtain;drape;drapery;mantle;pall,book,bannister;banister;balustrade;balusters;handrail,door;double;door,booth;cubicle;stall;kiosk,bed,stairs;steps,person;individual;someone;somebody;mortal;soul,desk,fireplace;hearth;open;fireplace,tray
id,,,,,,,,,,,,,,,,
10000_91.03441834_29.63851099_201608_0.jpg,0.006616,0.414203,0.0,0.071173,0.0,0.0,0.0,0.0,0.000068,0.0,0.0,0.00000,0.000000,0.0,0.0,0.0
10000_91.03441834_29.63851099_201608_180.jpg,0.085094,0.090968,0.0,0.055938,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,0.0,0.0
10000_91.03441834_29.63851099_201608_270.jpg,0.048906,0.354977,0.0,0.031290,0.0,0.0,0.0,0.0,0.000277,0.0,0.0,0.00000,0.000000,0.0,0.0,0.0
10000_91.03441834_29.63851099_201608_90.jpg,0.032631,0.275576,0.0,0.038755,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000,0.000613,0.0,0.0,0.0
10000_91.03441834_29.63851099_202107_0.jpg,0.005023,0.420267,0.0,0.055734,0.0,0.0,0.0,0.0,0.000001,0.0,0.0,0.00196,0.000535,0.0,0.0,0.0

In [81]:
# len(df1.columns)
_sky = df1.columns[[2]]
_plant = df1.columns[[13,17,66,94]]
_building = df1.columns[[0,1,32,48]]
_road = df1.columns[[87,6,52,11,38,136]]
_sky.tolist()

['sky']

In [133]:
# 天-3
# 植被 植物-18-67 地形-95-14
# 建筑物 建筑 2- 墙-1 围栏-33 摩天大楼-49
# 路 道路-88-7-53 人行道-12 杆-39 红绿灯 交通号志-137
indicator_matrix = pd.DataFrame()  
# 计算列'A', 'B' 和 'C' 的和，并将结果添加为新列'Sum_ABC'  
indicator_matrix['Sum_sky'] = df1[_sky.tolist()].sum(axis=1)  
indicator_matrix['Sum_plant'] = df1[_plant.tolist()].sum(axis=1)  
indicator_matrix['Sum_building'] = df1[_building.tolist()].sum(axis=1)  
indicator_matrix['Sum_road'] = df1[_road.tolist()].sum(axis=1)  
  
# 删除列'A', 'B' 和 'C'  
# df1.drop(['A', 'B', 'C'], axis=1, inplace=True)  
indicator_matrix.head()  
# len(df2)

,Sum_sky,Sum_plant,Sum_building,Sum_road
id,,,,
10000_91.03441834_29.63851099_201608_0.jpg,0.414203,0.000000,0.098611,0.456483
10000_91.03441834_29.63851099_201608_180.jpg,0.090968,0.000103,0.141032,0.378297
10000_91.03441834_29.63851099_201608_270.jpg,0.354977,0.001546,0.083507,0.409052
10000_91.03441834_29.63851099_201608_90.jpg,0.275576,0.000000,0.082914,0.422850
10000_91.03441834_29.63851099_202107_0.jpg,0.420267,0.000000,0.094377,0.436431

In [134]:
import pandas as pd  
  
  
# 打开第二个CSV文件，并读取全部数据（或者你也可以指定需要读取的列）  
file_path2 = r'e:\work\spatio_evo_urbanvisenv_svi\sv\perception_score.csv'  # 替换为你的第二个CSV文件的路径  
df2 = pd.read_csv(file_path2)  
  
# 设置第一列为索引值  
df2.set_index(df2.columns[0], inplace=True) 
df2.head()

,beautiful,boring,depressing,lively,safety,wealthy
iamge_name,,,,,,
12918_91.05522806_29.64954467_201309_90.jpg,0.000000,39.400436,68.050960,99.605637,95.704077,39.924045
11825_91.03004569_29.64412556_201309_180.jpg,3.285165,30.129652,56.102032,85.511819,96.274949,35.580360
8643_91.1233995_29.6433565_201309_180.jpg,4.066005,41.776000,61.552374,84.885707,85.884543,57.484489
5560_91.11352399_29.68657253_201608_270.jpg,4.246289,66.321016,31.815333,99.653947,96.209332,42.033324
13932_91.2051021_29.6430633_202108_0.jpg,4.499184,62.730503,90.665665,60.439160,32.649207,20.660156

In [135]:
# 合并两个DataFrame对象的数据  
# 这里使用'inner'合并方式，只会保留两个DataFrame中都有的索引值对应的数据行  
indicator_matrix = indicator_matrix.join(df2, how='inner')  
# indicator_matrix = indicator_matrix.reset_index() 
# indicator_matrix.drop(indicator_matrix.columns[[0,1]].tolist(), axis=1, inplace=True)  

indicator_matrix.head()
# indicator_matrix.columns[[0,1]].tolist()
# indicator_matrix.to_csv(r'E:\work\spatio_evo_urbanvisenv_svi\sv\indicator_matrix.csv', index=False)

,Sum_sky,Sum_plant,Sum_building,Sum_road,beautiful,boring,depressing,lively,safety,wealthy
id,,,,,,,,,,
10000_91.03441834_29.63851099_201608_0.jpg,0.414203,0.000000,0.098611,0.456483,61.944516,50.724910,6.227618,99.614003,96.473348,53.200920
10000_91.03441834_29.63851099_201608_180.jpg,0.090968,0.000103,0.141032,0.378297,56.007618,26.336406,39.057055,99.513836,89.717814,61.008584
10000_91.03441834_29.63851099_201608_270.jpg,0.354977,0.001546,0.083507,0.409052,49.953620,45.893384,14.466769,98.851410,96.282161,54.238255
10000_91.03441834_29.63851099_201608_90.jpg,0.275576,0.000000,0.082914,0.422850,57.879966,44.518444,19.328890,99.133417,95.422670,49.825774
10000_91.03441834_29.63851099_202107_0.jpg,0.420267,0.000000,0.094377,0.436431,49.611780,69.485802,30.301945,99.613096,96.538061,72.170171

In [138]:
indicator_matrix.head()

,Sum_sky,Sum_plant,Sum_building,Sum_road,beautiful,boring,depressing,lively,safety,wealthy
id,,,,,,,,,,
10000_91.03441834_29.63851099_201608_0.jpg,0.414203,0.000000,0.098611,0.456483,61.944516,50.724910,6.227618,99.614003,96.473348,53.200920
10000_91.03441834_29.63851099_201608_180.jpg,0.090968,0.000103,0.141032,0.378297,56.007618,26.336406,39.057055,99.513836,89.717814,61.008584
10000_91.03441834_29.63851099_201608_270.jpg,0.354977,0.001546,0.083507,0.409052,49.953620,45.893384,14.466769,98.851410,96.282161,54.238255
10000_91.03441834_29.63851099_201608_90.jpg,0.275576,0.000000,0.082914,0.422850,57.879966,44.518444,19.328890,99.133417,95.422670,49.825774
10000_91.03441834_29.63851099_202107_0.jpg,0.420267,0.000000,0.094377,0.436431,49.611780,69.485802,30.301945,99.613096,96.538061,72.170171

In [139]:
indicator_matrix_01 = indicator_matrix.reset_index()

In [140]:
# indicator_matrix.drop(indicator_matrix.columns[[0,1]].tolist(), axis=1, inplace=True)  

indicator_matrix_01.head()
# indicator_matrix.columns[[0,1]].tolist()

,id,Sum_sky,Sum_plant,Sum_building,Sum_road,beautiful,boring,depressing,lively,safety,wealthy
0,10000_91.03441834_29.63851099_201608_0.jpg,0.414203,0.000000,0.098611,0.456483,61.944516,50.724910,6.227618,99.614003,96.473348,53.200920
1,10000_91.03441834_29.63851099_201608_180.jpg,0.090968,0.000103,0.141032,0.378297,56.007618,26.336406,39.057055,99.513836,89.717814,61.008584
2,10000_91.03441834_29.63851099_201608_270.jpg,0.354977,0.001546,0.083507,0.409052,49.953620,45.893384,14.466769,98.851410,96.282161,54.238255
3,10000_91.03441834_29.63851099_201608_90.jpg,0.275576,0.000000,0.082914,0.422850,57.879966,44.518444,19.328890,99.133417,95.422670,49.825774
4,10000_91.03441834_29.63851099_202107_0.jpg,0.420267,0.000000,0.094377,0.436431,49.611780,69.485802,30.301945,99.613096,96.538061,72.170171

In [141]:
indicator_matrix_01.to_csv(r'E:\work\spatio_evo_urbanvisenv_svi\sv\indicator_matrix.csv', index=False)

In [166]:
indicator_matrix.iloc[:,0]
# type(indicator_matrix_01.iloc[:,0])

import pandas as pd  
from sklearn.preprocessing import MinMaxScaler   
  
# 初始化MinMaxScaler  
scaler = MinMaxScaler(feature_range=(0, 1))  

for i in range(len(indicator_matrix.columns)):

    indicator_matrix_index = indicator_matrix.columns[[i]].tolist()
    indicator_matrix[indicator_matrix_index] = scaler.fit_transform(indicator_matrix[indicator_matrix_index])
    
indicator_matrix.head()

,Sum_sky,Sum_plant,Sum_building,Sum_road,beautiful,boring,depressing,lively,safety,wealthy
id,,,,,,,,,,
10000_91.03441834_29.63851099_201608_0.jpg,0.530283,0.000000,0.098843,0.633720,0.619445,0.507249,0.062276,0.996140,0.964733,0.532009
10000_91.03441834_29.63851099_201608_180.jpg,0.116461,0.000106,0.141364,0.525176,0.560076,0.263364,0.390571,0.995138,0.897178,0.610086
10000_91.03441834_29.63851099_201608_270.jpg,0.454458,0.001586,0.083704,0.567873,0.499536,0.458934,0.144668,0.988514,0.962822,0.542383
10000_91.03441834_29.63851099_201608_90.jpg,0.352806,0.000000,0.083109,0.587028,0.578800,0.445184,0.193289,0.991334,0.954227,0.498258
10000_91.03441834_29.63851099_202107_0.jpg,0.538046,0.000000,0.094599,0.605882,0.496118,0.694858,0.303019,0.996131,0.965381,0.721702

In [173]:
indicator_matrix_01 = indicator_matrix.reset_index() 
indicator_matrix_01.to_csv(r'E:\work\spatio_evo_urbanvisenv_svi\sv\indicator_matrix_normalization.csv', index=False)

In [191]:
i = indicator_matrix.columns[0]
# i
# indicator_matrix[[i]]
# indicator_matrix[i].tolist()
indicator_matrix.head(10)

,Sum_sky,Sum_plant,Sum_building,Sum_road,beautiful,boring,depressing,lively,safety,wealthy
id,,,,,,,,,,
10000_91.03441834_29.63851099_201608_0.jpg,0.530283,0.000000,0.098843,0.633720,0.619445,0.507249,0.062276,0.996140,0.964733,0.532009
10000_91.03441834_29.63851099_201608_180.jpg,0.116461,0.000106,0.141364,0.525176,0.560076,0.263364,0.390571,0.995138,0.897178,0.610086
10000_91.03441834_29.63851099_201608_270.jpg,0.454458,0.001586,0.083704,0.567873,0.499536,0.458934,0.144668,0.988514,0.962822,0.542383
10000_91.03441834_29.63851099_201608_90.jpg,0.352806,0.000000,0.083109,0.587028,0.578800,0.445184,0.193289,0.991334,0.954227,0.498258
10000_91.03441834_29.63851099_202107_0.jpg,0.538046,0.000000,0.094599,0.605882,0.496118,0.694858,0.303019,0.996131,0.965381,0.721702
10000_91.03441834_29.63851099_202107_180.jpg,0.111396,0.003333,0.183193,0.454796,0.584444,0.289483,0.496052,0.994173,0.967571,0.721500
10000_91.03441834_29.63851099_202107_270.jpg,0.417087,0.000829,0.141760,0.506156,0.582401,0.502746,0.243238,0.996149,0.963485,0.637541
10000_91.03441834_29.63851099_202107_90.jpg,0.406243,0.000862,0.088467,0.522901,0.516314,0.528525,0.189026,0.996141,0.963419,0.611076
10001_91.03391009_29.63843157_201608_0.jpg,0.520558,0.000704,0.096699,0.611434,0.632385,0.596494,0.307276,0.996138,0.962171,0.464782
10001_91.03391009_29.63843157_201608_180.jpg,0.309924,0.001140,0.140079,0.524993,0.660180,0.392593,0.374089,0.996118,0.960643,0.736534